### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/adni_train_scaled_corrected.csv'

### ISSUE THREAD

**Issue by 011211** [tjiagoM/adni_phenotypes#1]
(adni_phenotypes) F:\2023\code\github\adni_phenotypes-main>python inference.py --dataset_location data/adni_test_scaled_corrected.csv --dataset_id adni
Namespace(dataset_id='adni', dataset_location='data/adni_test_scaled_corrected.csv', device='cuda:1', do_single_pass=False, wb_model_id='2cxy59fk')
wandb: Network error (ProxyError), entering retry loop.
Traceback (most recent call last):
  File "inference.py", line 124, in <module>
    run_inference(dataset_location=args.dataset_location, dataset_id=args.dataset_id,
  File "inference.py", line 60, in run_inference
    model = SimpleMLP(dim_in=155, dropout_rate=best_run.config['dropout']).to(device)
  File "F:\anaconda3\envs\adni_phenotypes\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "F:\anaconda3\envs\adni_phenotypes\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "F:\anaconda3\envs\adni_phenotypes\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "F:\anaconda3\envs\adni_phenotypes\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by 011211** [comment]
I followed the instructions in the readme.txt and used the command to download the dataset, but I get the above error, please tell me how I can fix it.

**Comment by tjiagoM** [comment]
Hi! And thanks for your interest in this work. You seem to be using the command as to use the ADNI dataset; however, I'm very sorry but we are not allowed to share the data directly. As you can see in our data availability statement in the paper, you have to request access yourself to access it: https://adni.loni.usc.edu/data-samples/access-data/


In the file `datasets.py` you can see which cortical and volume variables we used from processing that data (i.e., variables `FEATURES_CORTICAL`, `FEATURES_VOLUME`, and `FEATURES_VOLUME_EXTRA`). 

The way we normalise and scale the data is explained in the paper, with corresponding code in a jupyter notebook here: `data/Preprocessing ADNI data.ipynb`


I hope this helps.
